# Copyright 2018 Roland Jäger

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# checkout all soubmodules
variables:
  GIT_SUBMODULE_STRATEGY: recursive

##########################################
# Thesis
##########################################
.template: &thesis_script
  script:
    - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode -shell-escape" thesis.tex

thesis:
  image: eyenseo/latex-archlinux
  <<: *thesis_script
  artifacts:
    paths:
      - thesis.pdf
    expire_in: 2 days
  except:
    - tags

thesis_release:
  image: eyenseo/latex-archlinux
  <<: *thesis_script
  artifacts:
    paths:
      - thesis.pdf
  only:
    - tags
